source 'https://rubygems.org'
gem 'middleman', '~> 3.3.12'
gem 'middleman3-sassc', '~> 0.0.1'
gem 'middleman-livereload', '~> 3.4.0'
gem 'middleman-blog', '~> 3.5.3'
gem 'middleman-syntax', '~> 2.1.0'
gem 'builder', '~> 3.2.2'
gem 'redcarpet', '~> 3.3.4'
